---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - greenworkload.platform.io
  resources:
  - sleepschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenworkload.platform.io
  resources:
  - sleepschedules/finalizers
  verbs:
  - update
- apiGroups:
  - greenworkload.platform.io
  resources:
  - sleepschedules/status
  verbs:
  - get
  - patch
  - update
