# permissions for end users to edit sleepschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sleepschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workload-sleeper
    app.kubernetes.io/part-of: workload-sleeper
    app.kubernetes.io/managed-by: kustomize
  name: sleepschedule-editor-role
rules:
- apiGroups:
  - greenworkload.platform.io
  resources:
  - sleepschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenworkload.platform.io
  resources:
  - sleepschedules/status
  verbs:
  - get
